GET http://localhost:5000/api/chats/67ecf98931b89e41999abb2d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ViZTc3YjUwMmI0NjJjNjU0ZDQ5MWIiLCJlbWFpbCI6ImhpbEByZS5mZCIsImlhdCI6MTc0NDgwNjM4NiwiZXhwIjoxNzQ0ODI3OTg2fQ.EI6KOvjDFYbEFfuf1zt5Mx8UIVDTFKbqgh0W0AEoRBs